name: pizza_app
description: "Fast food delivery project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  add_to_cart_animation: ^2.0.4
  bloc: ^8.1.4
  cloud_firestore: ^5.4.2
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  firebase_auth: ^5.2.0
  firebase_core: ^3.3.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  iconly: ^1.0.1
  intl: ^0.19.0
  ionicons: ^0.2.2
  lottie: ^3.1.2
  navigation_view: ^1.0.6
  pizza_repository:
    path: packages/pizza_repository
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  shimmer: ^3.0.0
  user_repository:
    path: packages/user_repository

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/animation/
    - assets/images/
