name: pizza_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  add_to_cart_animation: ^2.0.4
  bloc: ^8.1.4
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  firebase_core: ^3.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  lottie: ^3.1.2
  pizza_repository:
    path: packages/pizza_repository
  user_repository:
    path: packages/user_repository

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/animation/
