name: pizza_repository
description: "The Repo that handles pizza"

publish_to: "none"

version: 0.0.1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cloud_firestore: ^5.2.1
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
